### ISSUE TITLE
CI: error in checkout action and macos labelled with turbovnc version

### ISSUE THREAD

**Issue by Giuncan** [RemoteConnectionManager/RCM#42]
Checkout action has wrong `ref`:
```yaml
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RCM
        uses: actions/checkout@v3
        with:
          repository: RemoteConnectionManager/RCM
          path: RCM
          ref: 'dev_update_2FA'
```
and macos artifacts has turbovnc label even if it is not included in the bundle.
